### ISSUE TITLE
Create sphinx documentation

### ISSUE THREAD

**Issue by Rafiot** [Lookyloo/har2tree#13]
Quite a few of the methods are documented, but we do not generate the documentation.

See https://www.sphinx-doc.org/en/master/usage/quickstart.html

And in order to publish it on read the docs: https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html

**Comment by Manoj13-coder** [comment]
I want to make documentation for this may i work on it?

**Comment by Rafiot** [comment]
Absolutely!

**Comment by Manoj13-coder** [comment]
Thanks may i send you PR on 1st of october? so, that my this contribution also be considered for hacktober contest

**Comment by Rafiot** [comment]
Sure, I'm assigning the issue to you.

**Comment by Manoj13-coder** [comment]
Thanks alot

**Comment by Rafiot** [comment]
Issue unassigned then, there was a misunderstanding.

The goal is to generate the documentation of har2tree using shpinx.
